// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Provides AI-powered style recommendations based on user preferences.
 *
 * - aiStyleRecommendation - A function that takes user style preferences and returns clothing recommendations.
 * - AIStyleRecommendationInput - The input type for the aiStyleRecommendation function.
 * - AIStyleRecommendationOutput - The return type for the aiStyleRecommendation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AIStyleRecommendationInputSchema = z.object({
  stylePreferences: z
    .string()
    .describe(
      'A detailed description of the user\u2019s style preferences, including preferred colors, materials, and clothing types.'
    ),
});
export type AIStyleRecommendationInput = z.infer<
  typeof AIStyleRecommendationInputSchema
>;

const AIStyleRecommendationOutputSchema = z.object({
  recommendations: z
    .string()
    .describe('A list of clothing item recommendations based on the user\u2019s style preferences.'),
});
export type AIStyleRecommendationOutput = z.infer<
  typeof AIStyleRecommendationOutputSchema
>;

export async function aiStyleRecommendation(
  input: AIStyleRecommendationInput
): Promise<AIStyleRecommendationOutput> {
  return aiStyleRecommendationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiStyleRecommendationPrompt',
  input: {schema: AIStyleRecommendationInputSchema},
  output: {schema: AIStyleRecommendationOutputSchema},
  prompt: `You are a personal stylist who provides clothing recommendations based on user preferences.

  Based on the following style preferences:
  {{stylePreferences}}

  Recommend clothing items that match these preferences.`,
});

const aiStyleRecommendationFlow = ai.defineFlow(
  {
    name: 'aiStyleRecommendationFlow',
    inputSchema: AIStyleRecommendationInputSchema,
    outputSchema: AIStyleRecommendationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
